### PR TITLE
Added health monitoring functions placeholders

### PR DESCRIPTION
**Pull request by lamaks**
#### Description of changes

Added health monitoring functions placeholders.

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Added relevant unit test for your changes. (`yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] Ran precheckin (`yarn precheckin`)

### CODE REVIEW

**Comment by devaradhanm** [comment]
Can you explain the responsibility of each funtion api you are adding in this PR?

**Comment by lamaks** [comment]
> Can you explain the responsibility of each funtion api you are adding in this PR?

The trigger function will runs in 5 minutes interval and start orchestration function. The orchestration function will call activity (client) function. The client function will call service api. Orchestration will have workflow to call rest api in a sequence with required delay. Orchestration function has restrictions on I/O operation that require to have client (activity) function.

**Comment by devaradhanm** [comment]
Can you also add why we need orchestration & activity function instead of doing the work in time trigger itself? what are the limitations of using time trigger other than that the execution time affects the next schedule time.

**Comment by lamaks** [comment]
> Can you also add why we need orchestration & activity function instead of doing the work in time trigger itself? what are the limitations of using time trigger other than that the execution time affects the next schedule time.

We need to persists scan id. Durable function can be handy here.
Orchestration I/O restriction https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-orchestrations#calling-http-endpoints

**Pull request merged**
