### PR TITLE
feat(axe-core-4.1.1): upgrade to axe-core 4.1.1 (including report support)

### PR DESCRIPTION
**Pull request by dbjorge**
#### Description of changes

This updates `axe-core`, `@axe-core/puppeteer`, and `accessibility-insights-report` in lockstep, including axe-core yarn resolutions.

It adds the new axe-core best-practice rules (from the rule table linked in the feature description) to the rule-exclusion list.

It also adds `accessibility-insights-report` as an external in the `web-api-scan-runner` webpack configuration; this means that rather than bundling it, the docker container will fetch the report package during its `npm install` phase. This prevents an error where the `report` package introduced a new runtime dependency which was not in turn treated as an external in the web-api-scan-runner; now, the scan runner will no longer need to care when the report package introduces new transitive deps.

#### Pull request checklist

- [x] Addresses an existing issue: Fixes 1797801
- [n/a] Added relevant unit test for your changes. (`yarn test`)
- [n/a] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)

### CODE REVIEW

**Review by lisli1 — DISMISSED** [review]
LGTM

**Review by lisli1 — APPROVED** [review]

**Comment by dbjorge** [comment]
I'm seeing an issue locally where a build of the CLI with these updates is failing at runtime; still investigating the root cause, but wanted to note here and block merge before it's understood

**Comment by dbjorge** [comment]
With #1178 merged, verified that  `yarn run pack` now produces output which is usable from outside the monorepo. Made a codepen exercising one of the new rules and verified that `npx ai-scan --url https://codepen.io/dbjorge/full/xxEqEab --restart` produces a report containing a failure in the new rule as expected.

**Review by lisli1 — APPROVED** [review]

**Comment by dbjorge** [comment]
In testing in a dev environment, it looks like the web-api-scan-runner package has a similar issue to what the scan CLI package hit. Testing a fix for that now.

**Comment by dbjorge** [comment]
Setting the report package as an external in the scan-runner package resolved the issue as expected; verified in a dev/test environment that submitting a scan request against a codepen page with a violation of one of the new axe-core rules (https://codepen.io/dbjorge/full/xxEqEab with a select-name violation) correctly results in a completed scan whose report includes the expected select-name violation.

**Review by lisli1 — APPROVED** [review]

**Pull request merged**
